const data = [
  {
    id: 1,
    title: 'Hunt 1',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/UB4UZMp.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 2,
    title: 'Hunt 2',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/GTI02nQ.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 3,
    title: 'Hunt 3',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/7zx9sAT.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 4,
    title: 'Hunt 4',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/JqGdpG3.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 5,
    title: 'Hunt 5',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/XUawwvp.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 6,
    title: 'Hunt 6',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/FQKHUmX.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 7,
    title: 'Hunt 7',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/wRN2zqk.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 8,
    title: 'Hunt 8',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/Acwl986.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 9,
    title: 'Hunt 9',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/qEtY2vy.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 10,
    title: 'Hunt 10',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/LrKPc3E.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 11,
    title: 'Hunt 11',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/ja7Ztkh.jpg',
    caption: 'Car Model + Car Type here',
  },
  {
    id: 12,
    title: 'Hunt 12',
    body: 'San Francisco, CA',
    imgUrl: 'https://i.imgur.com/G6T8vb1.jpg',
    caption: 'Car Model + Car Type here',
  },
]

export default data
